name: "CLA Assistant"

on:
  workflow_call:
    secrets:
      CLA_SIGNATURE_PUSH_TOKEN:
        required: true

permissions:
  actions: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_SIGNATURE_PUSH_TOKEN }}
        with:
          path-to-signatures: '.cla-signatures/v1.json'
          path-to-document: 'https://github.com/aileron-projects/.github/blob/main/CLA.md'
          branch: 'main'
          allowlist: bot*
          remote-organization-name: aileron-projects
          remote-repository-name: .github
